# src/daily/models.py
"""Data models for the Daily System (057–061).

All intermediate JSON files share these structures so that each script
can consume the output of the previous one without coupling to file layout.
"""

from __future__ import annotations

from dataclasses import asdict, dataclass, field
from typing import Any, Dict, List, Optional


# ── 057: Raw close input ──────────────────────────────────────────

@dataclass
class CloseRawInput:
    """Raw evening close log captured by 057."""
    date: str                              # YYYY-MM-DD
    raw_text: str                          # free-form close log
    satisfaction: Optional[int] = None     # 1–5
    energy_level: Optional[str] = None     # Low / Medium / High
    timestamp: str = ""                    # ISO 8601
    # Audio/voice metadata (057 voice input)
    input_mode: str = "interactive"        # text | file | audio_file | browser_recorded_audio | browser_recorded_audio_wizard | interactive
    audio_path: Optional[str] = None       # path to single audio file (non-wizard voice input)
    transcript_path: Optional[str] = None  # path to assembled transcript .txt
    transcript_chars: Optional[int] = None # character count of transcript
    transcription_engine: Optional[str] = None  # e.g. "whisper-1"
    language: Optional[str] = None         # ISO 639-1 language used
    # Wizard-specific fields
    sections: Optional[List[Dict[str, Any]]] = None  # per-section metadata list
    value_domains: Optional[List[str]] = None         # value domains tagged by user

    def to_dict(self) -> Dict[str, Any]:
        return asdict(self)

    @classmethod
    def from_dict(cls, d: Dict[str, Any]) -> "CloseRawInput":
        return cls(**{k: v for k, v in d.items() if k in cls.__dataclass_fields__})


# ── 058: Structured close output ──────────────────────────────────

@dataclass
class StructuredItem:
    """A single classified item from the close log."""
    text: str
    category: str       # Done / Progress / Blocker / OpenQuestion
    people: List[str] = field(default_factory=list)
    purpose: str = ""
    value_domains: List[str] = field(default_factory=list)

    def to_dict(self) -> Dict[str, Any]:
        return asdict(self)


@dataclass
class CloseStructured:
    """Structured output of 058."""
    date: str
    items: List[StructuredItem] = field(default_factory=list)
    structured_summary: str = ""
    provisional_top3: List[str] = field(default_factory=list)
    value_domains: List[str] = field(default_factory=list)
    research_candidates: List[str] = field(default_factory=list)
    contact_candidates: List[str] = field(default_factory=list)
    open_questions: List[str] = field(default_factory=list)
    friction_blockers: List[str] = field(default_factory=list)
    stage: str = "structured"

    def to_dict(self) -> Dict[str, Any]:
        d = asdict(self)
        d["items"] = [i.to_dict() for i in self.items]
        return d

    @classmethod
    def from_dict(cls, d: Dict[str, Any]) -> "CloseStructured":
        items = [StructuredItem(**i) for i in d.pop("items", [])]
        return cls(items=items, **{k: v for k, v in d.items() if k in cls.__dataclass_fields__})


# ── 059: Next-day preparation ────────────────────────────────────

@dataclass
class MeetingBrief:
    """A meeting brief generated by 059."""
    title: str
    date: str
    people: List[str] = field(default_factory=list)
    purpose: str = ""
    context: str = ""
    key_questions: str = ""
    desired_outcomes: str = ""
    prep_checklist: str = ""
    links_materials: str = ""
    status: str = "Draft"
    created_by: str = "Auto"
    related_event_ids: List[str] = field(default_factory=list)
    daily_log_id: str = ""

    def to_dict(self) -> Dict[str, Any]:
        return asdict(self)


@dataclass
class FollowUp:
    """A follow-up action generated by 059."""
    title: str
    date: str
    due_date: str = ""
    source: str = "Research"          # Meeting / Research / Monitoring / Personal
    status: str = "Open"
    priority: str = "P1"              # P0 / P1 / P2
    assignee: str = ""
    draft_message: str = ""
    next_action: str = ""
    notes: str = ""

    def to_dict(self) -> Dict[str, Any]:
        return asdict(self)


@dataclass
class NextDayPrep:
    """Output of 059."""
    date: str
    meeting_briefs: List[MeetingBrief] = field(default_factory=list)
    follow_ups: List[FollowUp] = field(default_factory=list)
    monitoring_suggestions: List[str] = field(default_factory=list)
    tomorrow_plan_raw: str = ""

    def to_dict(self) -> Dict[str, Any]:
        d = asdict(self)
        d["meeting_briefs"] = [m.to_dict() for m in self.meeting_briefs]
        d["follow_ups"] = [f.to_dict() for f in self.follow_ups]
        return d

    @classmethod
    def from_dict(cls, d: Dict[str, Any]) -> "NextDayPrep":
        briefs = [MeetingBrief(**m) for m in d.pop("meeting_briefs", [])]
        fups = [FollowUp(**f) for f in d.pop("follow_ups", [])]
        return cls(
            meeting_briefs=briefs,
            follow_ups=fups,
            **{k: v for k, v in d.items() if k in cls.__dataclass_fields__},
        )


# ── 060: Morning commit ──────────────────────────────────────────

@dataclass
class CommitItem:
    """A single morning commit (today's top-priority task)."""
    title: str
    rank: int
    status: str = "Planned"           # Planned / Doing / Done / Dropped
    why: str = ""
    definition_of_done: str = ""
    planned_time_block: str = ""
    estimated_minutes: int = 0
    order: int = 0
    value_domains: List[str] = field(default_factory=list)
    notes: str = ""

    def to_dict(self) -> Dict[str, Any]:
        return asdict(self)


@dataclass
class MorningCommit:
    """Output of 060."""
    date: str
    energy_level: str = "Medium"      # Low / Medium / High
    time_budget_hrs: float = 0.0
    final_top3: List[str] = field(default_factory=list)
    commits: List[CommitItem] = field(default_factory=list)

    def to_dict(self) -> Dict[str, Any]:
        d = asdict(self)
        d["commits"] = [c.to_dict() for c in self.commits]
        return d

    @classmethod
    def from_dict(cls, d: Dict[str, Any]) -> "MorningCommit":
        commits = [CommitItem(**c) for c in d.pop("commits", [])]
        return cls(commits=commits, **{k: v for k, v in d.items() if k in cls.__dataclass_fields__})
